name: Deploy with LFTP and Hash Check

on:
  push:
    branches: [ "main3" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y lftp

      - name: Generate hash diff
        run: |
          python3 deploy.py

      - name: Upload modified files
        run: |
          while IFS= read -r filepath; do
            echo "Uploading $filepath"
            lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} -e "put -O /python_app/ $filepath; bye" ftp://${{ secrets.FTP_HOST }}
          done < .deploy-to-upload.txt

      - name: Commit updated hash file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .deploy-hashes
          git commit -m "Update deploy hashes" || echo "No changes to commit"
          git push