name: Deploy via LFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Sync files via LFTP
        run: |
          lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }} <<EOF
          set ftp:ssl-allow no
          set net:timeout 120
          set net:max-retries 3
          set net:reconnect-interval-base 10
          mirror -R -v --only-newer ./ /public_html/ -x .git/ -x .github/ -x venv/
          quit
          EOF

