name: Deploy via LFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Sync files via LFTP
        run: |
          lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} -e "
            set ftp:ssl-allow no;
            set net:timeout 60;
            set ftp:passive-mode true;  # ¡Clave para cPanel!
            mirror -R -v -X .git/ -X .github/ -X venv/ ./ /public_html/;
            exit
          " ${{ secrets.FTP_HOST }}

