name: Deploy via LFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Sync files via LFTP
        run: |
            lftp -d -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ftp://${{ secrets.FTP_HOST }} <<EOF
            set ftp:ssl-allow no
            set net:timeout 120
            set ftp:passive-mode on
            set ftp:prefer-epsv no
            set net:max-retries 3
            mirror -R -v --only-newer --no-perms \
            -X .git/ \
            -X .github/ \
            -X venv/ \
            -X __pycache__/ \
            -X *.pyc \
            -X .env \
            -X staticfiles/ \
            -X db-respaldo.sqlite3 \
            ./ /python_app/
            bye
            EOF