name: Deploy via LFTP (Más estable)

on:
  push:
    branches: [ "main" ]      # Se activa al hacer push a "main"

jobs:
  deploy:
    runs-on: ubuntu-latest    # Usa un servidor Ubuntu para el despliegue

    steps:
      - uses: actions/checkout@v4  # Descarga código de GitHub

      - name: Install LFTP         # Instala LFTP (herramienta más robusta que FTP)
        run: sudo apt-get install -y lftp

      - name: Sync files via LFTP  # Sincroniza solo archivos modificados
        run: |
          lftp -e "
            set ftp:ssl-allow no;  # Desactiva SSL (más estable para conexiones problemáticas)
            set net:timeout 60;    # Evita que la conexión se cierre rápido
            mirror -R -v --only-newer ./ /public_html/
              -x .git/             # Excluye la carpeta .git
              -x .github/          # Excluye la carpeta .github
              -x venv/;            # Excluye el entorno virtual
            quit
          " -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}

